apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    app: calculator-cd
spec:
  selector:
    app: calculator-cd
  ports:
    - protocol: TCP
      port: 80          # The port that clients will connect to
      targetPort: 5000  # The port your container listens on 
  type: LoadBalancer
